apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: <service-name>-aws-secret
  namespace: <namespace>
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: <secret-store-name>
    kind: SecretStore
  target:
    name: <secret-name>
    template:
      data:
        REGISTRY_ENCRYPTION_KEY: "{{ .REGISTRY_ENCRYPTION_KEY }}"
        DB_ENCRYPTION_KEY: "{{ .DB_ENCRYPTION_KEY }}"
        REGISTRY_PRIVATE_KEY: |-
          {{ .REGISTRY_PRIVATE_KEY }}
        REGISTRY_PUBLIC_KEY: |-
          {{ .REGISTRY_PUBLIC_KEY }}
  data:
  - secretKey: REGISTRY_ENCRYPTION_KEY
    remoteRef:
      key: <secret-key>
      property: REGISTRY_ENCRYPTION_KEY
  - secretKey: DB_ENCRYPTION_KEY
    remoteRef:
      key: <secret-key>
      property: DB_ENCRYPTION_KEY
  - secretKey: REGISTRY_PRIVATE_KEY
    remoteRef:
      key: <secret-key>
      property: REGISTRY_PRIVATE_KEY
  - secretKey: REGISTRY_PUBLIC_KEY
    remoteRef:
      key: <secret-key>
      property: REGISTRY_PUBLIC_KEY