apiVersion: v1
kind: Secret
metadata:
  name: <service-name>-secrets
  namespace: <namespace>
  annotations:
    reloader.stakater.com/match: "true"  # Enable automatic pod reload when secrets change
type: Opaque
stringData:
  # Database Configuration
  DATABASE_URL: "postgresql://<username>:<password>@<hostname>:<port>/<dbname>"
  
  # Redis Configuration
  REDIS_URL: "rediss://<hostname>.<region>.cache.amazonaws.com:<port>"
  
  # Other secrets
  INTERNAL_API_KEY: "<base64-encoded-32-byte-key>"
  JWT_SECRET_KEY: "<base64-encoded-32-byte-key>"