apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: <secret-store-name>
  namespace: <namespace>
spec:
  provider:
    aws:
      service: SecretsManager
      region: <aws-region>
      auth:
        jwt:
          serviceAccountRef:
            name: <service-account-name>