name: OSV-Scanner

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install OSV-Scanner
      run: |
        pip install osv-scanner
    - name: Run OSV-Scanner
      run: |
        osv-scanner --json > results.json
    - name: Upload scan results
      uses: actions/upload-artifact@v4
      with:
        name: scan-results
        path: results.json
