name: OSV-Scanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run OSV Scanner
        run: osv-scanner --json > results.json

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: results.json
